image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: ubuntu:latest
  script:
   - apt-get update && apt-get install -y git npm
   - npm install
  artifacts:
    paths:
      - devopsatv1/ 

test:
  stage: test
  script:
    - docker run jessica/repoatvdevops:latest npm install
    - docker run jessica/repoatvdevops:latest npm test

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push jessica/repoatvdevops:latest
