image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:16
  script:
    - ls
    - npm install
  artifacts:
    paths:
      - build/

test:
  stage: test
  image: node:16
  script:
    - ls
    - npm install
    - npm test

deploy:
  stage: deploy
  image: docker:latest
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker push jessica/repoatvdevops:latest
