name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  test:
    image: ubuntu:latest
    stage: test
    script:
      - echo "Teste bem sucedido"

  deploy:
    image: ubuntu:latest
    stage: deploy
    script:
      - echo "Deploy bem sucedido"
