stages:         
  - build
  - test
  - deploy

build-job:       
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

unit-test-job:   
  stage: test    
  script:
    - echo "Code coverage is 90%"

lint-test-job:   
  stage: test    
  script:
    - echo "No lint issues found."

deploy-job:      
  stage: deploy  
  environment: production
  script:
    - echo "Deploying..."
    - echo "Tudo pronto!"
