name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: SAST scan
        uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"

  deploy-job:
      runs-on: ubuntu-latest
      needs: test-job
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Build Docker image
          run: docker build -t eronbetine/pucpr:latest .

        - name: Push Docker image
          run: docker push eronbetine/pucpr:latest